In [3]:
import pandas as pd

ventas = pd.read_csv(r"C:\Users\SAHUA\Documents\datascience-g8\01-python-intro\data\ventas.csv",
    dtype={"precio_unitario":"float64"})
ventas["import"]=ventas["unidades"]*ventas["precio_unitario"]

In [5]:
ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   float64
 7   descuento        1165 non-null   float64
 8   import           1200 non-null   float64
dtypes: float64(3), int64(1), str(5)
memory usage: 84.5 KB

In [4]:
ventas

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,import
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130.0,0.00,650.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320.0,0.00,4480.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280.0,0.00,280.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200.0,0.00,12000.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130.0,0.10,260.0
...,...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45.0,0.00,180.0
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200.0,0.05,15600.0
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320.0,0.05,640.0
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320.0,0.00,1920.0
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45.0,0.00,360.0

In [7]:
ventas.groupby("region")["import"].sum()

region
Centro    705695.0
Este      549745.0
Norte     862360.0
Oeste     626295.0
Sur       699920.0
Name: import, dtype: float64

In [8]:
ventas[ventas["region"]=="Sur"]["import"].sum()

np.float64(699920.0)

In [9]:
ventas.groupby("region")["import"].agg(["sum","mean","count"])

             sum         mean  count
region
Centro  705695.0  2594.466912    272
Este    549745.0  3054.138889    180
Norte   862360.0  2827.409836    305
Oeste   626295.0  3085.197044    203
Sur     699920.0  2916.333333    240

In [11]:
ventas.groupby("region")["import"].agg(suma="sum",promedio="mean",cantidad="count")

            suma     promedio  cantidad
region
Centro  705695.0  2594.466912       272
Este    549745.0  3054.138889       180
Norte   862360.0  2827.409836       305
Oeste   626295.0  3085.197044       203
Sur     699920.0  2916.333333       240

In [12]:
ventas.groupby(["region","categoria"])["import"].agg(suma="sum",promedio="mean",cantidad="count")

                       suma     promedio  cantidad
region categoria
Centro Accesorios   56895.0   605.265957        94
       Mobiliario  201520.0  2651.578947        76
       Tecnologia  447280.0  4385.098039       102
Este   Accesorios   44585.0   675.530303        66
       Mobiliario  136520.0  2730.400000        50
       Tecnologia  368640.0  5760.000000        64
Norte  Accesorios   78630.0   639.268293       123
       Mobiliario  200130.0  2668.400000        75
       Tecnologia  583600.0  5454.205607       107
Oeste  Accesorios   40205.0   628.203125        64
       Mobiliario  156170.0  2692.586207        58
       Tecnologia  429920.0  5307.654321        81
Sur    Accesorios   57800.0   642.222222        90
       Mobiliario  155320.0  2724.912281        57
       Tecnologia  486800.0  5234.408602        93

In [13]:
ventas.groupby("region").agg({
    "import":["sum","mean","max"],
    "unidades":["sum"],
    "producto":["nunique"]
})

          import                       unidades producto
             sum         mean      max      sum  nunique
region
Centro  705695.0  2594.466912  15600.0     1933        8
Este    549745.0  3054.138889  16800.0     1384        8
Norte   862360.0  2827.409836  16800.0     2166        8
Oeste   626295.0  3085.197044  15600.0     1469        8
Sur     699920.0  2916.333333  16800.0     1779        8